### ISSUE TITLE
 key not displayed properly in configuration section

### ISSUE THREAD

**Issue by LeFl0w** [Linty-Services/sonar-modelsim-plugin#1]
Go to the configuration panel "code coverage" => "Modelsim" => keys
The sonarqube coverage type key has not the right formatting it displays branch instead of sonar.modelsim...

![image](https://user-images.githubusercontent.com/11613152/66103561-74544880-e5b6-11e9-8162-9e9a6e3c4545.png)

**Comment by mroca1** [comment]
Key display fixed in commit "Fix key name"
